# Generated by Django 2.1.2 on 2019-04-08 19:47

import boogie.fields.enum_field
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pastebin.enums
import pastebin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_name', models.CharField(max_length=40, validators=[pastebin.models.check_valid_file_name], verbose_name='File name')),
                ('file_type', boogie.fields.enum_field.EnumField(pastebin.enums.Format, max_length=4, verbose_name='File type')),
                ('content', models.TextField(verbose_name='Contents')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.CharField(max_length=300, unique=True, verbose_name='Full path')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pastebin.Path')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paste',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pastebin.Path'),
        ),
        migrations.AlterUniqueTogether(
            name='paste',
            unique_together={('path', 'file_name')},
        ),
    ]
