# Generated by Django 2.2 on 2019-04-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dontpad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paste',
            options={'verbose_name': 'Paste', 'verbose_name_plural': 'Pastes'},
        ),
        migrations.AlterModelOptions(
            name='path',
            options={'verbose_name': 'Path', 'verbose_name_plural': 'Paths'},
        ),
    ]
