# Generated by Django 2.0.4 on 2018-05-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_simpeuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpeUser',
            new_name='SimpleUser',
        ),
    ]
