# Generated by Django 2.0.4 on 2018-05-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180502_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleUser',
        ),
    ]
